apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aiohttp-framework
  name: aiohttp-framework
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: aiohttp-framework
  type: NodePort
status:
  loadBalancer: {}
