apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aiohttp-framework
  name: aiohttp-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiohttp-framework
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aiohttp-framework
    spec:
      containers:
      - image: docker.io/krishbharath/aiohttp-framework
        env:
        - name: GUNICORN_RELOAD
          valueFrom:
            configMapKeyRef:
              key: gunicorn_reload
              name: aiohttp-framework
        - name: GUNICORN_BIND
          valueFrom:
            configMapKeyRef:
              key: gunicorn_bind
              name: aiohttp-framework
        - name: GUNICORN_WORKERS
          valueFrom:
            configMapKeyRef:
              key: gunicorn_workers
              name: aiohttp-framework
        - name: GUNICORN_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: gunicorn_loglevel
              name: aiohttp-framework
        name: aiohttp-framework
        resources: {}
status: {}
